# Generated by Django 3.2.9 on 2021-11-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211114_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guardianmore',
            old_name='designation',
            new_name='occupation',
        ),
        migrations.RenameField(
            model_name='historicalguardianmore',
            old_name='designation',
            new_name='occupation',
        ),
        migrations.AddField(
            model_name='guardianmore',
            name='yearly_income',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='historicalguardianmore',
            name='yearly_income',
            field=models.FloatField(default=0.0),
        ),
    ]
