# Generated by Django 3.2 on 2021-11-15 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_user_sex'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('duration_month', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_status', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Institude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eiin', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.ImageField(blank=True, default='istitude/default.jpg', null=True, upload_to='institude/logo')),
                ('cover', models.ImageField(blank=True, default='istitude/cover.jpg', null=True, upload_to='institude/cover')),
                ('sliders', models.ImageField(blank=True, default='istitude/sliders.jpg', null=True, upload_to='institude/sliders')),
                ('category', models.CharField(choices=[('play', 'play'), ('nursary', 'nursary'), ('prac-primary', 'prac-primary'), ('primary', 'primary'), ('High school', 'High school'), ('College', 'College'), ('University', 'University'), ('cadet', 'cadet'), ('madrasha', 'madrasha'), ('PhD', 'PhD'), ('Coaching_centre', 'Coaching_centre')], max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('contact_phones', models.CharField(max_length=100)),
                ('contact_emails', models.CharField(max_length=100)),
                ('contact_others', models.CharField(max_length=100)),
                ('established_date', models.DateField()),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.address')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institudes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
