# Generated by Django 3.2 on 2021-11-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institude', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institude',
            name='contact_emails',
            field=models.EmailField(max_length=254),
        ),
    ]
