# Generated by Django 3.2 on 2021-11-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institude', '0002_alter_institude_contact_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentstatus',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
