# Generated by Django 3.2 on 2021-11-17 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('institude', '0004_alter_paymentstatus_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteGroups',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
                ('institutes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grps', to='institude.institude')),
            ],
            options={
                'verbose_name_plural': 'Institute_Groups',
                'ordering': ['name'],
            },
            bases=('auth.group',),
        ),
    ]
